services:
  - type: web
    name: trivia-arena-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: ./hack-14ae1-firebase-adminsdk-fbsvc-53bb47d937.json
